# Name shown in the administration interface
name = "My first public connector"

# Code that will printed in the logs
code = "my-first-public-connector"

# This value should be the same as the one returned by the method "ExampleConnector.getConnectorId"
connector_id = "public-connector"

# Enable or disable the connector (Handled by the scanner by default)
enabled = true

#### Properties specific to your connector ####
# The configuration properties are available as parameter of the method "ExampleConnector.getConnectorId"
authentication {
    username = "my_username"
    password = "my_password"
}

some {
    nullable_property = null
    #optional_property = 42
}

some.important.boolean = true